### ISSUE TITLE
Trouble running the latest StanSample.jl on Windows 10

### ISSUE THREAD

**Issue by sreedta8** [StanJulia/Stan.jl#107]
Hi

I tried to install StanSample.jl in Julia via the Conda method: (I'm using Windows 10, Julia 1.6.2- I'm a beginner with Julia, very comfortble with R and Python )

Conda-based Method: I created a ```conda``` based stan-env (followed instructions in the Stan.jl installation page). Launched ```julia``` from the activated environment ```stan-env```and the ```CMDSTAN``` variable was set to the newly created ```stan-env```

At the prompt ```julia>```when I tried to ```add StanSample@5.3.0```, it gives the following error. 

I get the following ERROR.
```
(@v1.6) pkg> add StanSample@5.3.0
    Updating registry at `C:\Users\sreedatta\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: 0.11.7-1.3.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.
11.7-1.3.1
 ├─restricted by compatibility requirements with LowRankModels [15d4e49f] to ver
sions: [0.11.7-0.19.4, 0.21.0-0.21.8]
 │ └─LowRankModels [15d4e49f] log:
 │   ├─possible versions are: 1.0.0-1.1.1 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only version
s 1.0.0-1.1.1
 ├─restricted by compatibility requirements with BayesNets [ba4760a4] to version
s: 0.13.0-1.3.1, leaving only versions: [0.13.0-0.19.4, 0.21.0-0.21.8]
 │ └─BayesNets [ba4760a4] log:
 │   ├─possible versions are: 3.0.0-3.3.5 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only version
s 3.0.0-3.3.5
 └─restricted by compatibility requirements with StanSample [c1514b29] to versio
ns: 1.2.0-1.3.1 — no versions left
   └─StanSample [c1514b29] log:
     ├─possible versions are: 0.0.1-5.4.0 or uninstalled
     └─restricted to versions 5.3.0 by an explicit requirement, leaving only ver
sions 5.3.0
```

Should I create a separate environment to run Stan / StanSample via Julia rather than use the default Julia environment? How can I rectify the above error? Anyhelp would be appreciated

Sree

**Comment by goedman** [comment]
Hi Sree,

The error is caused by LowRankModels.jl in the sense that it forces a pretty old version of DataFrames.jl.

Do you need LowRankModels for your work/this project? If so you could try to `dev` LowRankModels and up the upper bound for DataFrames to v1.2 (from the current v0.21).

Hope this helps, otherwise we can look for another solution.

After you installed the stan-env, can you run the Bernoulli example? That has nothing to do with the shown error, just that the the installation of Stan’s cmdstan was successful. 

Rob

Rob J Goedman
***@***.***
