### ISSUE TITLE
download cmdstan as artifact

### ISSUE THREAD

**Issue by filchristou** [StanJulia/Stan.jl#119]
are there plans to download `cmdstan` as an artifact rather than having to manually install it ?
It would be so much easier for a beginner to just do `] add Stan` and start coding.

**Comment by goedman** [comment]
Hi @filchristou 

That has been attempted many times without success. Stan needs a compiler (written in Occam) to translate Stan Language programs to C++ and subsequently compiles and links that newly generated C++ code into the cmdstan executable.

On which platform do you work? For Linux and MacOS I suggest using git, on windows the coda route.

Rob

**Comment by filchristou** [comment]
I work in Linux and it was just needed to download cmdstan-2.30.1.tar.gz from https://github.com/stan-dev/cmdstan/releases

**Comment by goedman** [comment]
Yip, that's the easier case.

Let me know if you need further help.

**Comment by filchristou** [comment]
No help needed. Just wondering if that could be automated as an artifact in the first place.
