### ISSUE TITLE
one problem and some  questions

### ISSUE THREAD

**Issue by math4mad** [StanJulia/Stan.jl#120]
1. problem 
typo
 [Version 8.1.0](https://stanjulia.github.io/Stan.jl/stable/VERSIONS/#Version-8.1.0)
 Support StanSanple.jl v5.3 multithreading in cmdstan

2. question 1:   how to plot  model
3. how to use julia's DataFrame'object at  stan model
4.

**Comment by goedman** [comment]
Hi @math4mad ,

Thanks for pointing out the typo, I'll fix it in the next release. As this is way down in the "Versions" section of the latest release (I think), which version of Stan.jl are you looking at?

In any case, plotting is not really part of Stan.jl or StanSample.jl as there are many options in Julia. I these days mostly use Makie and Pluto in projects such as RegressionAndOtherStories. Although relatively new, that might be a good start the understand how to plot and use DataFrames with Stan.

Do you have Stan's CmdStan installed and built? Which platform are you using (Linux, MacOS, Windows)?

Rob

**Comment by math4mad** [comment]
> Hi @math4mad ,
> 
> Thanks for pointing out the typo, I'll fix it in the next release. As this is way down in the "Versions" section of the latest release (I think), which version of Stan.jl are you looking at?
> 
> In any case, plotting is not really part of Stan.jl or StanSample.jl as there are many options in Julia. I these days mostly use Makie and Pluto in projects such as RegressionAndOtherStories. Although relatively new, that might be a good start the understand how to plot and use DataFrames with Stan.
> 
> Do you have Stan's CmdStan installed and built? Which platform are you using (Linux, MacOS, Windows)?
> 
> Rob

1. about typo  In Versions sections, I  find  since  ver9.5.0  has problem . 

2. about  plot.   Actually , my question is : I  don't know  how to extract  params.  better has some demo

3. makie is great library,  maybe  contribute  a demo  to [beautiful.makie.org ](https://beautiful.makie.org)

4. Yeah , I already built and  installed   `CmdStan` , several demos work fine.   My computer is m1  MacBook Pro. MacOS:12.6 . When I installed c++ tool chain  application from  github , got  error information, I don't know why , but when  I test   command, it works!.  I remember last year I  installed an  cross-platform application  framework. here  it is [Tauri](https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-macos). Seems another way  to install c++ tool chain for MacOS . Many people stuck in this place?

5. As for  installation,  this repo [stan in docker](https://github.com/JBris/stan-cmdstanr-docker)  is a  good  routine.

**Comment by goedman** [comment]
Hi @math4mad 

Maybe it is better to use a MWE:

```
# StanSample & GLMakie must be available from your environment.

using StanSample, GLMakie

model = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
    y ~ bernoulli(theta);
}
";

sm = SampleModel("bernoulli", model);

data = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1]);

rc = stan_sample(sm; num_chains=4, data);

if success(rc)
  df = read_samples(sm, :dataframe);
  df |> display
end

density(df.theta) |> display
```

**Comment by goedman** [comment]
A more complete  example using RegresssionAndOtherStories.jl and Pluto.jl can be found [here](https://github.com/RegressionAndOtherStoriesJulia/ROSStanPluto.jl/blob/main/notebooks/Playgrounds/Stan/Stan.jl).
