### ISSUE TITLE
Access log density and gradient from a stan model

### ISSUE THREAD

**Issue by sethaxen** [StanJulia/Stan.jl#121]
It is sometimes useful to be able to be able to directly compute the log density of a Stan model given values of the (un)constrained parameters. For example, this allows inference methods implemented in Julia to be tested directly on all models in posteriordb without first porting all of these models to a Julia PPL.

Currently [BridgeStan.j](https://github.com/roualdes/bridgestan/tree/main/julia)l (unregistered) provides this functionality, via the following functions:
- https://roualdes.github.io/bridgestan/languages/julia.html#BridgeStan.log_density
- https://roualdes.github.io/bridgestan/languages/julia.html#BridgeStan.log_density_gradient

Would you be open to adding similar functions to Stan.jl? If so, to which subpackage should they belong?

**Comment by goedman** [comment]
Hi Seth,

BridgeStan is included in StanSample.jl. An example of how it can be used is included in the bernoulli.jl example in that package. It should be kind of "automatic" if you install bridgestan next to cmdstan (see the README in StanSample.jl).
In my setup I have "./StanSupport/cmdstan" and "./StanSupport/bridgestan".

Please let me know if those instructions can be made clearer or if you see any other improvements to the existing code in the example.

Rob

**Comment by sethaxen** [comment]
@goedman thanks! I hadn't seen that this was included. I had a few suggestions to make this more automatic. Unlike cmdstan, bridgestan requires no installation. Also, upon loading, I get a warning that the bridgestan path isn't set, so I as the user need to set the path. But StanSample knows the path; it checks it before including BridgeStan. So perhaps one of the following makes sense:
1. StanSample checks the `$BRIDGESTAN` environment variable if set. This allows the user to install bridgestan where they like
2. StanSample sets the `$BRIDGESTAN` environment variable once it finds bridgestan, which is one less set-up step for the user
3. StanSample packages bridgestan itself as a data dependency. This can be done using [git subtree](https://www.atlassian.com/git/tutorials/git-subtree), which enters the bridgestan code into version control of the repo or using a solution like DataDeps.jl, which would download the bridgestan repo upon request.

**Comment by goedman** [comment]
Thanks @sethaxen. I've not seen that warning, so maybe I should install the latest version of Edward's repo. I'll try that first.

All three suggested approaches look fine to me. Solution 3 is probably the hardest for me (not an in-depth git user) but might be the best approach if BridgeStan is added "automatically" to CI testing.

I'll try to reconstruct the warning first to see if the warning came from BridgeStan.jl itself or from `create_smb()` itself?

**Comment by sethaxen** [comment]
> All three suggested approaches look fine to me. Solution 3 is probably the hardest for me (not an in-depth git user) but might be the best approach if BridgeStan is added "automatically" to CI testing.

I've done solution 3 before on a repo and would be happy to open a PR including instructions for how to to maintain it. 

> I'll try to reconstruct the warning first to see if the warning came from BridgeStan.jl itself or from `create_smb()` itself?

I didn't run `create_smb` yet, so I think it came from BridgeStan itself. This line: https://github.com/roualdes/bridgestan/blob/main/julia/src/BridgeStan.jl#L40

**Comment by goedman** [comment]
If you don't mind making a PR, that would be great! Thanks.

**Comment by goedman** [comment]
Yip, the latest version of BridgeStan.jl breaks my setup. But the code looks cleaner/simpler. I'll hold off for your PR before continuing.

**Comment by goedman** [comment]
The problem was that in the latest version of the BridgeStan repo the module name was all lower case. Just wanted to make sure I understood what was happening. I want push these changes to StanSample.jl.
