### ISSUE TITLE
samples in csv file prevent consecutive runs of a model

### ISSUE THREAD

**Issue by itsdfish** [StanJulia/Stan.jl#128]
Hey Rob. I hope you are doing well!

I noticed that it is not possible to run models multiple times. I receive an error saying that one of the csv files containing the samples is locked. I think it should throw an error on any model.

**Comment by goedman** [comment]
Hi Chris, Here all is going fine, hope the same on your side!

Ran some tests but can't create this issue.

Maybe my understanding of the issue is not correct. What I did:

1. Used the bernoulli.jl and bernoulli2.jl examples in Stan.jl/Examples
2. Ran it in the REPL. bernoulli.jl creates a tmpdir using mktempdir(), bernoulli2.jl stores the results in ./tmp
3. Created a SampleModel (once only)
4. Executed stan_sample()
5. Read in the samples, e.g. df = read_samples(sm, :dataframe)
6. Executed stan_sample() again
7. Compared the first 10 or values in the df, they're different:
```
8000×1 DataFrame
  Row │ theta    
      │ Float64  
──────┼──────────
    1 │ 0.730307
    2 │ 0.730307
    3 │ 0.21217
    4 │ 0.447832

and

8000×1 DataFrame
  Row │ theta     
      │ Float64   
──────┼───────────
    1 │ 0.853284
    2 │ 0.853284
    3 │ 0.730558
    4 │ 0.0860013
```
for bernoulli.jl

Does that represent what you're trying to do?

Rob

**Comment by itsdfish** [comment]
My apologies. I was in a hurry, but I should have taken my time to provide an MWE. I cannot produce the problem on Linux, but I can produce it in Windows. I receive the error when I run the script below multiple times in the same session. It does not always happen immediately. Maybe after 3-8 times. It happens every time in my actual code. I'm not sure what the difference is aside from the model, but unfortunately I cannot share it at this time. 

**Code**

```
using Pkg
cd(@__DIR__)
Pkg.activate("")
using StanSample
using MCMCChains
ProjDir = @__DIR__

bernoullimodel = "

data {
  int<lower=0> N;
  array[N] int<lower=0, upper=1> y;
}

parameters {
  real<lower=0,upper=1> theta;
}

model {
  theta ~ beta(1,1);
  y ~ bernoulli(theta);
}

";

observed_data = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

# Default for tmpdir is to create a new tmpdir location

# To prevent recompilation of a Stan progam, choose a fixed location,

tmpdir= ProjDir * "/tmp"

sm = SampleModel("bernoulli2", bernoullimodel, tmpdir);

rc = stan_sample(sm; data=observed_data,
    save_warmup=false, num_warmups=1000,
    num_chains = 4,
    seed = 3,
    num_samples=1000);

read_samples(sm, :mcmcchains)
```

**Error**
```

# ERROR: IOError: unlink("c:\\Users\\.julia\\dev\\sandbox/tmp\\bernoulli2_chain_1.csv"): resource busy or locked (EBUSY)
# Stacktrace:
#  [1] uv_error
#    @ .\libuv.jl:100 [inlined]
#  [2] unlink(p::String)
#    @ Base.Filesystem .\file.jl:972
#  [3] rm(path::String; force::Bool, recursive::Bool)
#    @ Base.Filesystem .\file.jl:283
#  [4] rm
#    @ .\file.jl:273 [inlined]
#  [5] stan_run(m::SampleModel; kwargs::Base.Pairs{Symbol, Any, NTuple{6, Symbol}, NamedTuple{(:data, :save_warmup, :num_warmups, :num_chains, :seed, :num_samples), Tuple{Dict{String, Any}, Bool, Vararg{Int64, 4}}}})
#    @ StanSample C:\Users\.julia\packages\StanSample\d9XFV\src\stanrun\stan_run.jl:117
#  [6] top-level scope
#    @ c:\Users\.julia\dev\sandbox\temp.jl:31
```

**Version**

```
Julia 1.9.2
MCMCChains 6.0.3
StanSample 7.4.2
```

**Comment by goedman** [comment]
Hi Chris, I will experiment a bit with your MWE but I think it is doing what I did this morning.

Need to check closed issues. If I’m not mistaken this is a Windows only issue and I couldn’t resolve it (this came up about 5 years ago, a long time ago at least) and has to do with not being able to delete files on Windows under certain conditions.

I wonder if you can insert a line deleting just the .csv files. I’m not behind my computer but will take a closer look tonight.

**Comment by goedman** [comment]
https://github.com/StanJulia/Stan.jl/issues/47#issuecomment-321933140

I’ve never seen this …\\sandbox/tmp\\… construct before.

Can you try joinpath(ProjDir, “tmp”)

**Comment by itsdfish** [comment]
@goedman, thanks for looking into this. I tried `joinpath` and received the same error, except the path had `\\` throughout.

**Comment by itsdfish** [comment]
I tried deleting the csv files with `rm` but received the same error.  This leads me to believe you are correct about Windows not allowing Julia to delete files. Do you know if this is a problem in RStan or R more generally?

**Comment by goedman** [comment]
Yes, that matches my recollection. For a split second I thought Julia creates this “sandbox” to circumvent this problem, e.g. when you’re running it in the .julia/packages directory (which is on purpose read only).

To understand the severity of the problem better, is the compile time of the model significant in your workflow? If you create a dummy file in your home directory, i.e, not under anything .julia/…, can you delete such a file from the REPL?

**Comment by goedman** [comment]
Not sure I’m the right person anymore to answer your Rstan and R question, but I do remember a remark in the Statistical Rethinking book/code that seem to point to similar problems.

Also confusing is your remark above “it doesn’t always happen the first time”, although it does in your real program. Unless in the MWE the workflow is different.

**Comment by itsdfish** [comment]
I experienced the same problem when I moved tmp to the home directory. 

Yeah. The problem seems to happen consistently on the second run of my real model, but less consistently with the MWE. Once it happens with the MWE it continues to throw the error until I restart Julia. The model is the only difference that I am aware of. Very strange. 

My guess is that the correct solution is not to use Windows, but unfortunately I am stuck with it for this particular project. =/

**Comment by itsdfish** [comment]
Given that this appears to be an OS problem, I will go ahead and close the issue and continue to feel justified in my disdain for Windows =)

Thanks for your help!

**Comment by goedman** [comment]
I’ve always stayed away from even trying this, but if compilation is too much of a burden, would it be possible to copy the stan model (.stan file), the data files and the generated .exe file(s) by stanc to a new directory? That would also require updating the path field in the SampleModel.

**Comment by itsdfish** [comment]
Interesting idea. Let me try that tomorrow and report back.

**Comment by goedman** [comment]
Hi Chris,

I tried the following (using the bernoulli2.jl example):

1. Removed ./tmp  (I did this using the editor after the initial test run of bernoulli2.jl)

In the REPL:

2. Executed `sm = SampleModel("bernoulli2", bernoullimodel, tmpdir);`

# At this point `sm.tmpdir` only contains 3 files: bernoulli2.stan, bernoulli2.hpp and bernoulli2.exe

3. Execute: `tmp2 = mktempdir()`
4. Copy the 3 files from sm.tmpdir to tmpdir2

5. Duplicate sm: `sm2 = deepcopy(sm)` # Probably copy(sm) will do as well

6. Updated sm2.tmpdir: `sm2.tmpdir = " /Users/rob/.julia/dev/Stan/Examples/Bernoulli/tmp2"`
7. Updated sm2.output_base: `sm2.output_base =  "/Users/rob/.julia/dev/Stan/Examples/Bernoulli/tmp2/bernoulli2"`

8. Executed: `rc = stan_sample(sm2; data=observed_data)`
9. Executed: `df2 = read_samples(sm2, :dataframe)`

This seems to work fine. Steps 2 to 8 could be captured in a function.

**Comment by itsdfish** [comment]
@goedman, thank you. That did work for me. If you need a quick solution, you can manually delete the files, which isn't too bad if you have two monitors.

**Comment by goedman** [comment]
You mean the .csv files? It's interesting these are actually created by cmdstan, not by Julia. Julia only sets up the command line to execute cmdstan.

As it has been a question asked over the years, I might try to document this somewhere. Thanks again for your help!

**Comment by goedman** [comment]
Famous final last words? Anyway, in Rel 10.4.2 I've added an example function (in Examples/Bernoulli/berboulli2.jl) that duplicates the tmpdir that should work on Windows. Just merged.
