### ISSUE TITLE
Excessive print of Stanmodel information on Mac

### ISSUE THREAD

**Issue by danmrc** [StanJulia/Stan.jl#63]
Hi,

This is more of an annoyance than a bug. I am using stan.jl with stan 2.20.0 in Atom. After I run `Stanmodel`, it prints that information of the summary **everytime** I use the repl for something.

Eg.:

```
bernoullistanmodel = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
    y ~ bernoulli(theta);
}
"

stanmodel = Stanmodel(name="bernoulli", model=bernoullistanmodel);
```

And it will print a bunch of information about the model. Now do something else, like `2+2`and it will print the info all over again. 

This is a Mac OS related bug, it does not happens on Windows. I am using Mojave.

Thanks in advance

**Comment by goedman** [comment]
Hi Daniel,

Hmm, I don't use Atom, so not sure yet how to reproduce this. I do use Mojave.

Is there a reason you still use Stan.jl (instead of CmdStan.jl)? I stopped actively maintaining Stan.jl about 2 years ago and I'm in fact in the process of completely redoing is over the next few months based on a set new packages (which are simpler to maintain I hope).

That will be a major breaking change, but I will keep CmdStan around and operational for at least 2 years. I think the old Stan.jl to CmdStan.jl is a minimal change. Or you can try the new StanSample.jl directly.

Best,
Rob

**Comment by danmrc** [comment]
> Is there a reason you still use Stan.jl (instead of CmdStan.jl)?

No, it is my first time using Stan and I didn't actually realised this (although there is an Important note). I apologize.

However, the same thing happens with CmdStan

**Comment by goedman** [comment]
Yip, just installed Atom and see the problem. Hmm, let me experiment a bit further. Is this the only time you see something like this?

**Comment by danmrc** [comment]
This just happens on Atom. 

I messed around a bit and if I comment out the if on stanmodel.jl, `show_model` (lines 207 - 215), this goes away.

**Comment by goedman** [comment]
Aah, that helps definitely, as I was testing the Stanmodel constructor and didn't get anywhere.

I might try to construct a MWE and ask on JuliaLang if others have seen this.

**Comment by danmrc** [comment]
I think I actually solved this. I was wrong about where was the bug. I messed around a lot, but the key thing is to put `::MIME"text/plain"` in show. I found this on [Juno documentation](http://docs.junolab.org/v0.7/man/info_developer.html). They say:

> This default rendering method will not be used if you define e.g.
>
> Base.show(io::IO, ::MIME"text/plain", ::Foo) = print(io, "Foo")
> 
> for displaying this nicely in the REPL. 

Here is a way to do it, but without defining that `model_show` (as I said, I messed stuff a bit): 

```
function Base.show(io::IO,::MIME"text/plain", m::Stanmodel)
  println("  name =                    \"$(m.name)\"")
  println("  nchains =                 $(m.nchains)")
  println("  num_samples =             $(m.num_samples)")
  println("  num_warmup =                $(m.num_warmup)")
  println("  thin =                    $(m.thin)")
  println("  monitors =                $(m.monitors)")
  println("  model_file =              \"$(m.model_file)\"")
  println("  data_file =               \"$(m.data_file)\"")
  println("  output =                  Output()")
  println("    file =                    \"$(m.output.file)\"")
  println("    diagnostics_file =        \"$(m.output.diagnostic_file)\"")
  println("    refresh =                 $(m.output.refresh)")
  println("  pdir =                   \"$(m.pdir)\"")
  println("  tmpdir =                 \"$(m.tmpdir)\"")
  println("  output_format =           :$(m.output_format)")
  if isa(m.method, Sample)
   sample_show(io, m.method, false)
  elseif isa(m.method, Optimize)
     optimize_show(io, m.method, false)
  elseif isa(m.method, Variational)
     variational_show(io, m.method, false)
   else
   diagnose_show(io, m.method, false)
  end
end
```

And the problem goes away! I hope this does not break stuff on the console, though

**Comment by goedman** [comment]
Looks like that might work (or at least a way forward).

Will test a bit more on the console as I saw some issues there with just the above change (sample_show to Base.show) when calling `stanmodel` afterwards.

**Comment by goedman** [comment]
After trying many variations, I haven't found one that works in both cases. I find the Juno documentation example pretty ridiculous, it just prints out a sting, "Foo" in the example, but that is not acceptable.

Your modification fails on my system if I just enter `stanmodel` to see the values after generating the Stanmodel object.

Will have a fresh look tomorrow.

**Comment by goedman** [comment]
This morning I tried once more to fix this issue, to no avail. Unfortunately I have no experience with Atom which makes debugging this issue a slow process. And I am simply running out of time.

It seems to me Atom is hanging (no prompt) until I select the correct window and press return. Why it keeps printing out a previous variable when entering a new instruction, like `2`, is unclear to me. On the master version of CmdStan.jl I have left a test_atom.jl script in the test directory to test a possible fix. Of course a PR that handles both the REPL and Atom is more than welcome!

Daniel's suggestion above is clearly a step in the right direction but I can't rework it into a solid solution.

**Comment by danmrc** [comment]
> I find the Juno documentation example pretty ridiculous, it just prints out a sting, "Foo" in the example, but that is not acceptable.

Yes, it should be better documented

> Your modification fails on my system if I just enter stanmodel to see the values after generating the Stanmodel object.

I am not sure I get this (probably because English is my second language), but this is that after entering `Stanmodel()` it does not print the info? You would have to do something like this to see the info:

```
obj = Stanmodel(args)
obj
``` 

If this is the problem, the fix is pretty simple. In `Stanmodel`just add:

```
  anss =  Stanmodel(name, nchains,
    num_warmup, num_samples, thin,
    id, model, model_file, monitors,
    data, data_file, cmdarray, method, random,
    init, init_file, output, printsummary, pdir, tmpdir, output_format);
    model_show(IOBuffer(),anss,false)
    return anss
```
Instead of just `StanModel` This would be around line 184 in stanmodel.jl

> Daniel's suggestion above is clearly a step in the right direction but I can't rework it into a solid solution.

I actually found another solution: just put `io`as the first argument of _every_ `println`, e.g. `println("  name =                    \"$(m.name)\"")`becomes `println(io, "  name =                    \"$(m.name)\"")`

This also solves the problem in Atom

**Comment by goedman** [comment]
If the last statement in a script is:
```
stanmodel = Stanmodel(...)
```
it should print the stanmodel.

If the last statement in a script is:
```
stanmodel = Stanmodel(...);
```
it should not print the stanmodel.

In most cases it is not the last statement as usually somewhere later in the script `stan(...)` is called. If I want to see what the stanmodel looks like the REPL I type:
```
stanmodel
```

I will try your 2nd suggestion!

**Comment by goedman** [comment]
Hi Daniel, can you try the master version of CmdStan?

**Comment by danmrc** [comment]
Just remind me of how it is done. It is just `add CmdStan@master`?

**Comment by goedman** [comment]
] add CmdStan#master

**Comment by danmrc** [comment]
That solved the problem. 

Thanks a lot!

**Comment by goedman** [comment]
Well, you solved it! Of course I’ll add you to the credits for the next release.

**Comment by danmrc** [comment]
Thanks a lot! I am glad I could help
