### ISSUE TITLE
Fix link in readme.md

### ISSUE THREAD

**Issue by ueliwechsler** [StanJulia/Stan.jl#68]
Most of the links in the readme.md file do not work. 
It would be nice if this could be fixed.

**Comment by goedman** [comment]
My apologies for this. My estimate is it will take about one more month to bring the documentation to a reasonable state. I will do a quick fix on just the README this week.

Best,
Rob

**Comment by ueliwechsler** [comment]
No problem at all. Thank you for your work.

**Comment by goedman** [comment]
Just merged a few few updates, Stan.jl v5.0.2.

Any feedback helps! Thanks.

**Comment by ueliwechsler** [comment]
Cool, thanks. The links are working now and the part in the documentation about the minimal installation requirements is really useful.
