### ISSUE TITLE
Stan 5.0.2 precompile warnings on Julia 1.3.

### ISSUE THREAD

**Issue by michael-prange** [StanJulia/Stan.jl#70]
I'm not sure if this is a problem, but when I did a package update this morning I saw that Stan was updated to 5.0.2. Then a precompile resulted in the following warnings. Just thought I'd mention it.

Michael

(v1.3) pkg> up
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed OpenBLAS_jll ───── v0.3.7+1
 Installed CSTParser ──────── v2.0.0
 Installed Arpack ─────────── v0.4.0
 Installed StatsFuns ──────── v0.9.2
 Installed JuliaInterpreter ─ v0.7.5
 Installed Stan ───────────── v5.0.2
 Installed Arpack_jll ─────── v3.5.0+2
 Installed Optim ──────────── v0.19.6
  Updating `~/.julia/environments/v1.3/Project.toml`
  [682df890] ↑ Stan v5.0.1 ⇒ v5.0.2
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [7d9fca2a] ↑ Arpack v0.3.1 ⇒ v0.4.0
  [68821587] + Arpack_jll v3.5.0+2
  [00ebfdb7] ↑ CSTParser v1.1.0 ⇒ v2.0.0
  [aa1ae85d] ↑ JuliaInterpreter v0.7.4 ⇒ v0.7.5
  [4536629a] + OpenBLAS_jll v0.3.7+1
  [429524aa] ↑ Optim v0.19.5 ⇒ v0.19.6
  [682df890] ↑ Stan v5.0.1 ⇒ v5.0.2
  [4c63d2b9] ↑ StatsFuns v0.8.0 ⇒ v0.9.2

(v1.3) pkg> precompile
Precompiling project...
Precompiling Stan
[ Info: Precompiling Stan [682df890-35be-576f-97d0-3d8c8b33a550]
WARNING: Method definition findall(Union{Base.Regex, AbstractString}, AbstractString) in module Base at regex.jl:345 overwritten in module StanBase at /Users/prange/.julia/packages/StanBase/uoK8W/src/utils/findall.jl:20.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #findall(Any, typeof(Base.findall), Union{Base.Regex, AbstractString}, AbstractString) in module Base overwritten in module StanBase.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition findall(Union{Base.Regex, AbstractString}, AbstractString) in module Base at regex.jl:345 overwritten in module StanBase at /Users/prange/.julia/packages/StanBase/uoK8W/src/utils/findall.jl:20.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #findall(Any, typeof(Base.findall), Union{Base.Regex, AbstractString}, AbstractString) in module Base overwritten in module StanBase.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition findall(Union{Base.Regex, AbstractString}, AbstractString) in module Base at regex.jl:345 overwritten in module StanBase at /Users/prange/.julia/packages/StanBase/uoK8W/src/utils/findall.jl:20.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #findall(Any, typeof(Base.findall), Union{Base.Regex, AbstractString}, AbstractString) in module Base overwritten in module StanBase.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition findall(Union{Base.Regex, AbstractString}, AbstractString) in module Base at regex.jl:345 overwritten in module StanBase at /Users/prange/.julia/packages/StanBase/uoK8W/src/utils/findall.jl:20.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #findall(Any, typeof(Base.findall), Union{Base.Regex, AbstractString}, AbstractString) in module Base overwritten in module StanBase.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition findall(Union{Base.Regex, AbstractString}, AbstractString) in module Base at regex.jl:345 overwritten in module StanBase at /Users/prange/.julia/packages/StanBase/uoK8W/src/utils/findall.jl:20.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #findall(Any, typeof(Base.findall), Union{Base.Regex, AbstractString}, AbstractString) in module Base overwritten in module StanBase.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition findall(Union{Base.Regex, AbstractString}, AbstractString) in module Base at regex.jl:345 overwritten in module StanBase at /Users/prange/.julia/packages/StanBase/uoK8W/src/utils/findall.jl:20.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition #findall(Any, typeof(Base.findall), Union{Base.Regex, AbstractString}, AbstractString) in module Base overwritten in module StanBase.
  ** incremental compilation may be fatally broken for this module **

(v1.3) pkg>

**Comment by goedman** [comment]
Thanks Michael, yes, that is a problem, final should not be re-defined in Julia 1.3 and up. I'll check that. Can you check with version of StanBase is installed on your system? Should be 1.0.3.

**Comment by michael-prange** [comment]
I just added StanBase and checked its status: v1.0.0. If Stan 5.0.2 needs StanBase 1.0.3, shouldn’t an add Stan result in the correct version of StanBase. Pardon my ignorance.

Michael

 pkg> add StanBase
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed QuadGK ────── v2.2.0
 Installed Polynomials ─ v0.6.0
  Updating `~/.julia/environments/v1.3/Project.toml`
  [d0ee94f6] + StanBase v1.0.0
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [f27b6e38] + Polynomials v0.6.0
  [1fd47b50] ↑ QuadGK v2.1.1 ⇒ v2.2.0

(v1.3) pkg> status StanBase
    Status `~/.julia/environments/v1.3/Project.toml`
  [d0ee94f6] StanBase v1.0.0

(v1.3) pkg>

**Comment by goedman** [comment]
Absolutely, but why it decides not to install StanBase v1.0.1, v1.0.2 or v1.0.3 baffles me. On my system, when I forced it to ‘add StanBase@1.0.2’ it downgraded the new version of MCMCChains (v0.4) to v0.3.5. These version ”storms” are very worrisome to me and taking way too much time to figure them out. I’ll have another go at it by clearing my .julia dir.

**Comment by michael-prange** [comment]
Rob,

If you want me to try any experiments, just let me know what to do.

Michael

**Comment by goedman** [comment]
Thanks Michael,

I'm planning to experiment a bit more today. At least I can up the lower bounds to v1.1 for all of StanJulia's packages (except CmdStan.jl) forcing usage of MCMCChains v0.4 and the 1.1 versions.

But want to check if that creates issues with incompatible versions between other packages on the default Julia environments (1.3 & 1.4). I rarely work in those anymore, I also work in projects, e.g. StatisticalRethinking.jl or Stan.jl.

In the past I've seen 2 reasons for these problems, either cached versions or "lurking" Pkg restrictions.

I'll report back later today. If not fixed by then, I would love to take you up on your offer! A fresh set of eye ...

Rob

**Comment by goedman** [comment]
Hi Micheal, would you mind trying it again, it should upgrade all StanJulia packages to v1.1 and Stan.jl itself to v5.1.0.

After re-reading the Pkg docs once more I wonder if versions with a major version of 0 could be more problematic then I expected (in this case SpecialFunctions.jl)..

**Comment by michael-prange** [comment]
Rob,

It seems to have worked. Here is the entire output of the update.

Michael

(v1.3) pkg> up
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed AbstractMCMC ────── v0.1.0
 Installed MacroTools ──────── v0.5.3
 Installed StanSample ──────── v1.1.1
 Installed StanBase ────────── v1.1.1
 Installed BinDeps ─────────── v1.0.0
 Installed Distributions ───── v0.21.11
 Installed Stan ────────────── v5.1.0
 Installed ProgressMeter ───── v1.2.0
 Installed FFMPEG ──────────── v0.2.4
 Installed DataFrames ──────── v0.20.0
 Installed MultivariateStats ─ v0.7.0
 Installed CategoricalArrays ─ v0.7.4
 Installed StanVariational ─── v1.1.2
 Installed Plots ───────────── v0.28.2
 Installed StanDiagnose ────── v1.1.1
 Installed StatsPlots ──────── v0.13.0
 Installed MCMCChains ──────── v0.4.1
 Installed StanOptimize ────── v1.1.1
  Updating `~/.julia/environments/v1.3/Project.toml`
  [c91e804a] ↓ Gadfly v1.1.0 ⇒ v1.0.1
  [682df890] ↑ Stan v5.0.2 ⇒ v5.1.0
  [d0ee94f6] ↑ StanBase v1.0.0 ⇒ v1.1.1
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [80f14c24] + AbstractMCMC v0.1.0
  [9e28174c] ↑ BinDeps v0.8.10 ⇒ v1.0.0
  [00ebfdb7] - CSTParser v2.0.0
  [324d7699] ↑ CategoricalArrays v0.5.5 ⇒ v0.7.4
  [a81c6b42] ↓ Compose v0.7.4 ⇒ v0.7.3
  [a93c6f00] ↑ DataFrames v0.19.4 ⇒ v0.20.0
  [864edb3b] ↑ DataStructures v0.15.0 ⇒ v0.17.6
  [31c24e10] ↑ Distributions v0.19.2 ⇒ v0.21.11
  [ffbed154] ↑ DocStringExtensions v0.7.0 ⇒ v0.8.1
  [c87230d0] ↑ FFMPEG v0.2.3 ⇒ v0.2.4
  [c91e804a] ↓ Gadfly v1.1.0 ⇒ v1.0.1
  [682c06a0] ↑ JSON v0.20.0 ⇒ v0.21.0
  [c7f686f2] ↑ MCMCChains v0.3.14 ⇒ v0.4.1
  [1914dd2f] ↑ MacroTools v0.5.1 ⇒ v0.5.3
  [6f286f6a] + MultivariateStats v0.7.0
  [91a5bcdd] ↑ Plots v0.27.1 ⇒ v0.28.2
  [92933f4c] + ProgressMeter v1.2.0
  [682df890] ↑ Stan v5.0.2 ⇒ v5.1.0
  [d0ee94f6] ↑ StanBase v1.0.0 ⇒ v1.1.1
  [fb13fc95] ↑ StanDiagnose v1.0.0 ⇒ v1.1.1
  [fbd8da12] ↑ StanOptimize v1.0.0 ⇒ v1.1.1
  [c1514b29] ↑ StanSample v1.0.0 ⇒ v1.1.1
  [6ede68ce] ↑ StanVariational v1.0.0 ⇒ v1.1.2
  [f3b207a7] ↑ StatsPlots v0.12.0 ⇒ v0.13.0
  [0796e94c] - Tokenize v0.5.7
  Building FFMPEG → `~/.julia/packages/FFMPEG/guN1x/deps/build.log`
  Building Plots ─→ `~/.julia/packages/Plots/2KhB2/deps/build.log`

(v1.3) pkg>

**Comment by goedman** [comment]
Great, thanks for trying!

**Comment by goedman** [comment]
Hi Michael, for now I'll close this issue. My hope id that the precompile warnings have gone. Please let me know if not.

Thanks for your help!

Best,
Rob

**Comment by michael-prange** [comment]
Rob,

The precompile warnings are gone. Thanks.

Michael
