### ISSUE TITLE
Any plan for direct c++ backend support

### ISSUE THREAD

**Issue by yebai** [StanJulia/Stan.jl#85]
The current `Stan.jl` uses the `CmdStan` backend, while  [`PyStan`](https://pystan.readthedocs.io/en/latest/index.html), the Python interface for Stan, directly works with Stan's C++ API, thus providing more functionalities, such as access to model's [log density ](https://pystan.readthedocs.io/en/latest/api.html#pystan.StanFit4model.log_prob)and [gradient](https://pystan.readthedocs.io/en/latest/api.html#pystan.StanFit4model.grad_log_prob) functions.  

Access to log density and gradient functions would make it straightforward to reuse Stan's DSL and math library, but with more choices for sampling methods, e.g. AdvancedHMC, DynamicHMC, AdvancedMH, emcee (currently via PyCall, but planed in AdvancedMH), nested sampling etc. 

Given that Julia has much better support for C and C++ FFI (e.g. [Cxx.jl](https://github.com/JuliaInterop/Cxx.jl)), does it make sense to explore an alternative approach for interfacing with Stan, e.g. directly work with its C++ APIs? 

cc @cpfiffer @xukai92

**Comment by yebai** [comment]
cc @tpapp

**Comment by yebai** [comment]
cc @sethaxen

**Comment by tpapp** [comment]
> Access to log density and gradient functions would make it straightforward to reuse Stan's DSL and math library, but with more choices for sampling methods, e.g. AdvancedHMC, DynamicHMC

I am not sure what you mean here. DynamicHMC and AdvancedHMC is basically Stan's NUTS, with minor variations.

In any case think that the whole HMC/NUTS stack can and should be implemented in pure Julia, which is much easier to maintain. Interfacing with C++ instead gives much lower returns to effort invested. FWIW, the bottleneck is AD but that is because Julia is a general programming language (as opposed to a DSL like Stan), but I think Zygote is getting there.

I used Stan these days for comparison, which is why I wrote some glue code for it, but I have no plans to make further investments in it; I would rather work in Julia.

**Comment by goedman** [comment]
Hi @yebai , this question has come up several times. At least one user has switched to PyCall/PyStan (for another reason) and reported it worked fine. This should give you access to more of Stan’s functionality.

It seems though your request has broader objectives and goes what Stan's diagnose method provides (access to computed gradients on the unconstrained scale and logdensities - section 12.6 of the Stan Reference Manual) or even the PyCall/PyStan route.

Over the years I have given a few of my considerations from about 7 or 8 years ago as I started the work on Stan.jl. Most of these are (technically at least) no longer true or less relevant (e.g. the state of Cxx.jl and maybe having to support different C++ compilers).

What remains is that I consider myself a user, not a developer. My real interest these days is in StatisticalRethinking (7 years ago in fact the ARM book by Gelman/Hill). If someone wants to step up and develop a C++ API based version I'm happy to pass on the baton.

If my understanding is correct, your suggestion seems to include:

1. Preserving Stan's DSL (the Stan Language program which is compiled by stanc (today stanc2, soonish to be replaced by stanc3, in Ocaml) into a C++ program. Currently stanc is decoupled from math library access. This is what I think of as the front-end part of cmdstan.

2. Implement the back-end logic (steps) of cmdstan in Julia by calling Stan's C++ API, as in PyStan and RStan. 

3. Over time investigate if by using the Stan Language to select different HMC engine implementations, e.g. DynamicHMC.jl, AdvancedHMC.jl, or supported SamplingAlgorithms, e.g. AdvancedMH is possible and/or beneficial.

As stated above I don’t feel 2 and 3 are worthwhile (or low hanging fruit) _**for me personally**_. Item 1 remains a bit of an issue in that the model is not easily accessible from within Julia and a few times I have considered writing a small, partial Stan Language parser, e.g. to retrieve and simulate the effect of the chosen priors in the model section. But haven’t done that yet.
