### ISSUE TITLE
Feedback wanted: Wrapper mode for cmdstan

### ISSUE THREAD

**Issue by rok-cesnovar** [StanJulia/Stan.jl#89]
Hi,

cmdstan/cmdstanr/cmdstanpy developers are thinking about making a wrapper-mode for cmdstan, which would make cmdstan more friendly for "machine consuming". In general wrapping cmdstan works ok, but there are some cases where it could be simplified or improved. We want to incorporate all the knowledge gathered from using these wrappers in the last year or so into making this wrapper mode, so we are also reaching out to the Stan julia developers for feedback.

There will be a formal proposal with more details in the near future, this is just a preliminary round. If this is not the best place for this discussion, I apologize and kindly ask to point me to a better location.

Current ideas:
- arguments are supplied via JSON file, so the call to cmdstan would be 
`./bernoulli wrapper-mode arg_file=args.json`

Where args.json is:
```json
{
    "sample" : {
        "num_samples": 2000
    },
    "output" : {
        "file": "path/to/file.csv"
     }
}
```
The organization of the JSON file would match the current argument structure.

- no initial metadata dump in stdout, all other stdout will be organized for simpler consumption (single line warnings/errors)

- metadata, inverse mass metric and stepsize would be reported in a separate file in JSON format for easier consumption

- the samples would be in a separate CSV file that would only have a header and samples (including warmup if requested). This will simplify reading in CSV files.

- a separate makefile for wrappers ("make/local" for wrappers)
the wrappers could place any makefile options, stancflags inside this file and would not interfere with make/local

Please let us know what you think of these suggestions, if JSON "plays well" with Julia and if you encountered any other difficulties wrapping Cmdstan. Thanks!

**Comment by goedman** [comment]
Rok,

It has never been a real problem to run the cmdstan executable (`./bernoulli` in your example) with the correct arguments.

The slightly trickier part is to parse the sample, optimize, adapt, seed, etc command arguments, e.g. to specify the seed value  in StanJulia:
```
sm = SampleModel("bernoulli", bernoullimodel,
  seed=StanSample.RandomSeed(seed=-1));
```
would results in inserting something like:
```
   ...
   },
   "seed" : {
     "-1"
   },
   ...
```
in the proposed .json file vs. today
```
 `/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_nh7Ub8/bernoulli sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_nh7Ub8/bernoulli_init_1.R id=1 data file=/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_nh7Ub8/bernoulli_data_1.R output file=/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_nh7Ub8/bernoulli_chain_1.csv refresh=100`
```

Thus, in the json approach I would generate a .json file for each chain (while parsing the Julia code). I do have a slight preference for the new json approach as it will be easier to read.

Splitting up the current chain output CSV files and make this work with `stansummary` is a major win!

The makefile suggestion, the final item in above list, is a bit unclear to me. Does it not interfere with the current `make/local` because it replaces that file?

Finally, although it doesn't bother me, is the `wrapper-mode` flag in fact necessary?

Best,
Rob

**Comment by rok-cesnovar** [comment]
Thanks for the feedback. Feel free to close the issue whenever.

> Does it not interfere with the current `make/local` because it replaces that file?

Essentially, it would behave the same as the current make/local. The proposing change is because cmdstanR/cmdstanpy do not want to touch the make/local files too much as a user could also wish to put something in there by themself. Its not a typical use case, but can happen.

An example is PRECOMPILED_HEADERS=true for windows users with Cmdstan 2.24. If the users have a recent-enough compiler on Windows they can use this flag to speedup compiling for 50%.

So make/local would be touched by the user manually (or via some helper functions) for setting flags that are intended to be set permanently. make/wrapper-local or whatever will be the final name would only be touched by the wrappers.

Wrappers could still do everything via make/local if they wanted to, this would not be a breaking change.

> Finally, although it doesn't bother me, is the `wrapper-mode` flag in fact necessary?

Hm, probably not. We could only use ./bernoulli wrapper_args = arg.json and that would mean the model was started in wrapper model. 

Another idea is to have separate executables for wrappers. So `make WRAPPER examples/berrnouli/bernoullii` would compile a different executable that would work in this wrapper friendly mode. 

These are all still proposals and in flux, nothing is set in stone. Just wanted your input before making an official proposal. Thanks!!
